// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ExportResult(arg1:string,arg2:string,arg3:string):Promise<main.RecognitionResponse>;

export function GetConfig():Promise<string>;

export function GetRecognitionStatus():Promise<Record<string, any>>;

export function LoadModel(arg1:string,arg2:string):Promise<main.RecognitionResponse>;

export function SelectAudioFile():Promise<Record<string, any>>;

export function StartRecognition(arg1:main.RecognitionRequest):Promise<main.RecognitionResponse>;

export function StopRecognition():Promise<main.RecognitionResponse>;

export function UpdateConfig(arg1:string):Promise<main.RecognitionResponse>;
