// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportResult(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExportResult'](arg1, arg2, arg3);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetRecognitionStatus() {
  return window['go']['main']['App']['GetRecognitionStatus']();
}

export function LoadModel(arg1, arg2) {
  return window['go']['main']['App']['LoadModel'](arg1, arg2);
}

export function SelectAudioFile() {
  return window['go']['main']['App']['SelectAudioFile']();
}

export function StartRecognition(arg1) {
  return window['go']['main']['App']['StartRecognition'](arg1);
}

export function StopRecognition() {
  return window['go']['main']['App']['StopRecognition']();
}

export function UpdateConfig(arg1) {
  return window['go']['main']['App']['UpdateConfig'](arg1);
}
