// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ExportResult(arg1:string,arg2:string,arg3:string):Promise<main.RecognitionResponse>;

export function GetAITemplates():Promise<Record<string, any>>;

export function GetAppRootDirectory():Promise<string>;

export function GetAudioDuration(arg1:string):Promise<Record<string, any>>;

export function GetConfig():Promise<string>;

export function GetModelInfo(arg1:string):Promise<Record<string, any>>;

export function GetRecognitionStatus():Promise<Record<string, any>>;

export function GetTemplateManagerInfo():Promise<Record<string, any>>;

export function LoadModel(arg1:string,arg2:string):Promise<main.RecognitionResponse>;

export function OnFileDrop(arg1:Array<string>):Promise<void>;

export function SelectAudioFile():Promise<Record<string, any>>;

export function SelectModelDirectory():Promise<Record<string, any>>;

export function SelectModelFile():Promise<Record<string, any>>;

export function StartRecognition(arg1:main.RecognitionRequest):Promise<main.RecognitionResponse>;

export function StopRecognition():Promise<main.RecognitionResponse>;

export function UpdateConfig(arg1:string):Promise<main.RecognitionResponse>;
